"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import SearchedContextProvider from "@/context/SearchedContextProvider";

const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <SearchedContextProvider>
      <html lang="en">
        <body className="relative bg-gray-100  ">
          <Navbar />
          {children}
        </body>
      </html>
    </SearchedContextProvider>
  );
}
